---
title       : Developing Data Products Course Project
subtitle    : Find the Best Car for You
author      : Beth Fioretta
job         : Insurance Company
logo        : Logo.jpg
framework   : io2012        
highlighter : highlight.js  
hitheme     : tomorrow       
mode        : selfcontained 
knit        : slidify::knit2slides
---

## INTRODUCTION
This presentation is for the Developing Data Products Course Project from Coursera. The assignment has two parts. 

* First, create a Shiny application and deploy it on Rstudio's servers. 

* Second, use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation for the application.  


Links:
* The application developed for the first part of the assignment is available at: https://bfioretta.shinyapps.io/developingdataproducts/  
* The presentation is available at: https://github.com/BFioretta/DevelopingDataProducts  
* Files for the presentation are available on GitHub: https://github.com/BFioretta/DevelopingDataProducts

---

## FIND THE BEST CAR FOR YOU SHINY APPLICATION
This application allows the user to find the best car for them based on their selections for Transmission type, Cylinder, MPG and HP preferences.  The application utilizes the mtcars dataset.  

* First, use the radio buttons to select whether you prefer a Manual or Automatic transmission.
* Then, use the check boxes to select one or more cyclinder options.
* Lastly, use the sliders to indicate your preference ranges for Horse Power (HP) and Miles Per Gallon (MPG).

* When all selections have been made, click on the Search button to refresh the listing on the right with the cars which fit the criteria chosen.

---

## MTCARS DATASET
The data utilized by the application is the mtcars dataset.  This data was provided by the 1974 Motor Trend US magazine.  It consists of fuel consumption and 10 other aspects of automomobile design and performance for 32 cars (1973-1974).
Below is a summary of the data:
```{r, echo=FALSE}
summary(mtcars)
```

---

## DATA FILTERING
The Shiny code uses a simple filter statement based on the selections by the user.
* am represents the Transmission choice
* cyl represents the Cylinder choice
* MilesPerGallon represents the MPG range chosen
* Horsepower represents the HP range chosen

Below is the actual filter statement used:
* data <- isolate(filter(data, Transmission %in% input$am, Cylinders %in% input$cyl, MilesPerGallon %in% mpg_seq, Horsepower %in% hp_seq))

---


